version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    external_links:
      - mongo
    environment: 
      - MONGO_URL=mongodb://mongo:27017/klangkeller
      - NODE_APP_INSTANCE=s10c
    volumes:
      - ./:/usr/src/app
    entrypoint: ["npm", "run", "dev"]
  mongo:
    image: mongo
    ports:
      - '27017:27017'
